"""Integration tests using committed fixtures.

Topology:   tests/fixtures/topology.yaml
Keys:       tests/fixtures/keys/{node}.yaml       (real key material, not generated by tests)
Expected:   tests/fixtures/configs/{node}/config.json + haproxy.cfg

Each test rebuilds the config in-memory from the committed topology + keys and
compares byte-for-byte (config.json) or string (haproxy.cfg) against the
committed expected output.  Both inputs and expected outputs are version-controlled,
so any divergence is a genuine rendering regression.

To regenerate expected outputs after an intentional change:
  uv run hexrift --yaml tests/fixtures/topology.yaml build --all --xray --haproxy \\
      --keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs
"""

from pathlib import Path

import orjson
import pytest

from hexrift.app import HexRiftApp
from hexrift.components.render.context import build_exit_context, build_hub_context
from hexrift.components.render.haproxy import render_haproxy
from hexrift.components.render.xray import build_exit_config, build_hub_config, serialize_config
from hexrift.constants import RegionType


FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
FIXTURE_TOPOLOGY = FIXTURES_DIR / "topology.yaml"
FIXTURE_KEYS_DIR = FIXTURES_DIR / "keys"
FIXTURE_CONFIGS_DIR = FIXTURES_DIR / "configs"

ALL_NODE_IDS = ["nlA00", "mskA00"]


def _build_for_node(node_id: str) -> tuple[bytes, str]:
    """Build xray config bytes + haproxy cfg for a node using committed keys."""

    app = HexRiftApp(yaml_path=FIXTURE_TOPOLOGY)
    region, node = app.schema.get_node(node_id)
    cfg = app.schema.config
    node_keys = app.keys.load_node_keys(node_id, FIXTURE_KEYS_DIR)

    if region.type == RegionType.EXIT:
        hub_nodes = [n for r in cfg.regions if r.type == RegionType.HUB for n in r.nodes]
        ctx = build_exit_context(cfg, region, node, node_keys, hub_nodes)
        xray_config = build_exit_config(ctx)
        haproxy_cfg = render_haproxy(ctx, RegionType.EXIT)
    else:
        exit_node_keys = {
            n.id: app.keys.load_node_keys(n.id, FIXTURE_KEYS_DIR)
            for r in cfg.regions
            if r.type == RegionType.EXIT
            for n in r.nodes
        }
        ctx = build_hub_context(cfg, region, node, node_keys, exit_node_keys)
        xray_config = build_hub_config(ctx)
        haproxy_cfg = render_haproxy(ctx, RegionType.HUB)

    return serialize_config(xray_config), haproxy_cfg


@pytest.mark.integration
def test_topology_parses_without_error(real_app: HexRiftApp):
    cfg = real_app.schema.config
    assert cfg.global_.namespace == "test.hexrift"


@pytest.mark.integration
def test_topology_node_count(real_app: HexRiftApp):
    assert len(real_app.schema.get_all_nodes()) == 2


@pytest.mark.integration
def test_topology_user_count(real_app: HexRiftApp):
    assert len(real_app.schema.config.users) == 2


@pytest.mark.integration
def test_topology_group_count(real_app: HexRiftApp):
    assert len(real_app.schema.config.groups) == 2


@pytest.mark.integration
def test_topology_region_count(real_app: HexRiftApp):
    assert len(real_app.schema.config.regions) == 2


@pytest.mark.integration
def test_exit_region_vless_route(real_app: HexRiftApp):
    exits = real_app.schema.get_exit_regions()
    assert exits[0].vless_route == 1000


@pytest.mark.integration
@pytest.mark.parametrize("node_id", ALL_NODE_IDS)
def test_config_json_matches_committed(node_id: str):
    generated, _ = _build_for_node(node_id)
    expected = (FIXTURE_CONFIGS_DIR / node_id / "config.json").read_bytes()
    expected = expected.replace(b"\r\n", b"\n")  # to nullify Windows CRLF
    assert generated == expected, (
        f"config.json mismatch for {node_id!r}.\n"
        "Regenerate with:\n"
        "  uv run hexrift --yaml tests/fixtures/topology.yaml build --all --xray "
        "--keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs"
    )


@pytest.mark.integration
@pytest.mark.parametrize("node_id", ALL_NODE_IDS)
def test_haproxy_cfg_matches_committed(node_id: str):
    _, generated = _build_for_node(node_id)
    expected_bytes = (FIXTURE_CONFIGS_DIR / node_id / "haproxy.cfg").read_bytes()
    expected = expected_bytes.replace(b"\r\n", b"\n").decode()
    generated = generated.replace("\r\n", "\n")
    assert generated == expected, (
        f"haproxy.cfg mismatch for {node_id!r}.\n"
        "Regenerate with:\n"
        "  uv run hexrift --yaml tests/fixtures/topology.yaml build --all --haproxy "
        "--keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs"
    )


@pytest.mark.integration
def test_exit_config_structure():
    generated, _ = _build_for_node("nlA00")
    cfg = orjson.loads(generated)

    # Top-level keys
    for key in ("log", "inbounds", "outbounds", "routing", "dns"):
        assert key in cfg

    # Reality inbound present
    inbound_tags = [ib["tag"] for ib in cfg["inbounds"]]
    assert "direct-xhttp" in inbound_tags

    # CDN inbound present (topology has cdn_xhttp_path for exit region)
    assert "cdn-xhttp" in inbound_tags

    # Standard outbounds present
    outbound_tags = [ob["tag"] for ob in cfg["outbounds"]]
    assert "direct" in outbound_tags
    assert "blocked" in outbound_tags
    assert "warp" in outbound_tags

    # Reality settings use the committed private key
    reality_inbound = next(ib for ib in cfg["inbounds"] if ib["tag"] == "direct-xhttp")
    private_key = reality_inbound["streamSettings"]["realitySettings"]["privateKey"]
    assert private_key == "2M_KKW_6GTmT87r70vuDeqFFmHKy9wmoaADNqUFueGI"

    # Decryption key is ML-KEM-768
    assert reality_inbound["settings"]["decryption"].startswith("mlkem768x25519plus.native.600s.7hyY0")


@pytest.mark.integration
def test_hub_config_structure():
    generated, _ = _build_for_node("mskA00")
    cfg = orjson.loads(generated)

    # No top-level reverse block (reverse is embedded per portal client)
    assert "reverse" not in cfg

    # Hub inbound has clients for all users + server + guests + portal clients
    direct_ib = next(ib for ib in cfg["inbounds"] if ib["tag"] == "direct-xhttp")
    client_emails = [c["email"] for c in direct_ib["settings"]["clients"]]
    assert "alice@test.hexrift" in client_emails
    assert "alice-server@alice" in client_emails
    assert "bob@test.hexrift" in client_emails
    assert "laptop@bob" in client_emails
    assert "phone@bob" in client_emails
    assert "home-portal@alice" in client_emails

    # Portal client carries the reverse tag; no catch-all routing rule for it
    portal_client = next(c for c in direct_ib["settings"]["clients"] if c["email"] == "home-portal@alice")
    assert portal_client.get("reverse") == {"tag": "home-portal"}
    rules = cfg["routing"]["rules"]
    assert not any(r.get("user") == ["home-portal@alice"] for r in rules)

    # CDN inbound only has cdn-access users (alice has cdn, bob does not)
    cdn_ib = next(ib for ib in cfg["inbounds"] if ib["tag"] == "cdn-xhttp")
    cdn_emails = [c["email"] for c in cdn_ib["settings"]["clients"]]
    assert "alice@test.hexrift" in cdn_emails
    assert "bob@test.hexrift" not in cdn_emails

    # Exit outbound present with correct public key
    outbound_tags = [ob["tag"] for ob in cfg["outbounds"]]
    assert "nlA00" in outbound_tags
    nl_outbound = next(ob for ob in cfg["outbounds"] if ob["tag"] == "nlA00")
    pub_key = nl_outbound["streamSettings"]["realitySettings"]["publicKey"]
    assert pub_key == "2SPCC3V_diQ97Pl6CYnFp52St-k7Mof9PNDPS9D4yRU"

    # Hub short IDs from committed groups
    short_ids = direct_ib["streamSettings"]["realitySettings"]["shortIds"]
    assert "aabbccddeeff0011" in short_ids  # main group explicit short_id
    assert "1122334455667788" in short_ids  # guest group explicit short_id

    # Decryption key is X25519
    assert direct_ib["settings"]["decryption"].startswith("mlkem768x25519plus.native.600s.wLmsb")


@pytest.mark.integration
def test_exit_haproxy_structure():
    _, haproxy = _build_for_node("nlA00")
    assert "bk_reality" in haproxy
    assert "*:443" in haproxy
    assert "[::]:443" in haproxy  # ipv6=true in exit defaults
    assert "crt-store" in haproxy  # CDN configured for nl region


@pytest.mark.integration
def test_hub_haproxy_structure():
    _, haproxy = _build_for_node("mskA00")
    assert "bk_reality" in haproxy
    assert "crt-store" in haproxy  # CDN configured for msk region
    assert "cdn-hub.test.hexrift" in haproxy


@pytest.mark.integration
def test_hub_routing_uses_exit_as_default():
    """hub_default: nl means catch-all routes to nlA00, not back to hub."""

    generated, _ = _build_for_node("mskA00")
    cfg = orjson.loads(generated)
    # Last routing rule is the catch-all; its outbound must be an exit node tag
    last_rule = cfg["routing"]["rules"][-1]
    assert last_rule["outboundTag"] == "nlA00"


@pytest.mark.integration
def test_hub_portal_routing_rule():
    """alice's home portal should appear as a routing rule."""

    generated, _ = _build_for_node("mskA00")
    cfg = orjson.loads(generated)
    rules = cfg["routing"]["rules"]
    portal_domain_rule = next((r for r in rules if r.get("domain") == ["home.alice.example.com"]), None)
    assert portal_domain_rule is not None
    assert portal_domain_rule["outboundTag"] == "home-portal"


@pytest.mark.integration
def test_hub_direct_routing_rule():
    """hub_routes direct rule for internal.example.com should be present."""

    generated, _ = _build_for_node("mskA00")
    cfg = orjson.loads(generated)
    rules = cfg["routing"]["rules"]
    direct_rule = next(
        (r for r in rules if r.get("outboundTag") == "direct" and "internal.example.com" in r.get("domain", [])),
        None,
    )
    assert direct_rule is not None
    assert "internal.example.com" in direct_rule["domain"]


@pytest.mark.integration
def test_exit_client_is_hub_exit_uuid():
    """nlA00's direct inbound should have the deterministic hub-exit UUID for mskA00."""

    generated, _ = _build_for_node("nlA00")
    cfg = orjson.loads(generated)
    clients = cfg["inbounds"][0]["settings"]["clients"]
    assert len(clients) == 1
    assert clients[0]["email"] == "mskA00-nlA00@test.hexrift"
    # UUID is deterministic: uuid5(ns, "mskA00-nlA00")
    assert clients[0]["id"] == "17d3c9f0-7373-5f77-9298-e18c4055e471"
