"""Integration tests using committed fixtures.

Topology:   tests/fixtures/topology.yaml
Keys:       tests/fixtures/keys/{node}.yaml       (real key material, not generated by tests)
Expected:   tests/fixtures/configs/{node}/config.json + haproxy.cfg

Each test rebuilds config in-memory from committed topology + keys and
compares byte-for-byte (config.json) or string (haproxy.cfg) against
committed expected output.  Both inputs and expected outputs are version-controlled,
so any divergence is genuine rendering regression.

To regenerate expected outputs after an intentional change:
  uv run hexrift --yaml tests/fixtures/topology.yaml build --all --xray --haproxy \\
      --keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs
"""

import json
from pathlib import Path

import pytest

from hexrift.app import HexRiftApp
from hexrift.components.derive.identity import Namespace
from hexrift.components.render.haproxy import render_haproxy
from hexrift.components.render.portal import build_portal_config
from hexrift.components.render.xray import build_exit_config, build_hub_config, serialize_config
from hexrift.constants import RegionType
from hexrift.inbounds.context import build_exit_context, build_hub_context


FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
FIXTURE_TOPOLOGY = FIXTURES_DIR / "topology.yaml"
FIXTURE_KEYS_DIR = FIXTURES_DIR / "keys"
FIXTURE_CONFIGS_DIR = FIXTURES_DIR / "configs"

ALL_NODE_IDS = ["nlA00", "mskA00"]


def _build_for_node(node_id: str) -> tuple[bytes, str]:
    """Build xray config bytes + haproxy cfg for node using committed keys."""

    app = HexRiftApp(yaml_path=FIXTURE_TOPOLOGY)
    region, node = app.schema.get_node(node_id)
    cfg = app.schema.config
    node_keys = app.keys.load_node_keys(node_id, FIXTURE_KEYS_DIR)

    if region.type == RegionType.EXIT:
        ctx = build_exit_context(cfg, region, node, node_keys)
        xray_config = build_exit_config(ctx)
        haproxy_cfg = render_haproxy(ctx)
    else:
        exit_node_keys = {
            n.id: app.keys.load_node_keys(n.id, FIXTURE_KEYS_DIR)
            for r in cfg.regions
            if r.type == RegionType.EXIT
            for n in r.nodes
        }
        ctx = build_hub_context(cfg, region, node, node_keys, exit_node_keys)
        xray_config = build_hub_config(ctx)
        haproxy_cfg = render_haproxy(ctx)

    return serialize_config(xray_config), haproxy_cfg


@pytest.mark.integration
def test_topology_parses_without_error(real_app: HexRiftApp):
    cfg = real_app.schema.config
    assert cfg.global_.namespace == "test.hexrift"


@pytest.mark.integration
def test_topology_node_count(real_app: HexRiftApp):
    assert len(real_app.schema.get_all_nodes()) == 2


@pytest.mark.integration
def test_topology_user_count(real_app: HexRiftApp):
    assert len(real_app.schema.config.users) == 2


@pytest.mark.integration
def test_topology_group_count(real_app: HexRiftApp):
    assert len(real_app.schema.config.groups) == 2


@pytest.mark.integration
def test_topology_region_count(real_app: HexRiftApp):
    assert len(real_app.schema.config.regions) == 2


@pytest.mark.integration
def test_exit_region_vless_route(real_app: HexRiftApp):
    exits = real_app.schema.get_exit_regions()
    assert exits[0].vless_route == 1000


@pytest.mark.integration
@pytest.mark.parametrize("node_id", ALL_NODE_IDS)
def test_config_json_matches_committed(node_id: str):
    generated, _ = _build_for_node(node_id)
    expected = (FIXTURE_CONFIGS_DIR / node_id / "config.json").read_bytes()
    expected = expected.replace(b"\r\n", b"\n")  # to nullify Windows CRLF
    assert generated == expected, (
        f"config.json mismatch for {node_id!r}.\n"
        "Regenerate with:\n"
        "  uv run hexrift --yaml tests/fixtures/topology.yaml build --all --xray "
        "--keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs"
    )


@pytest.mark.integration
@pytest.mark.parametrize("node_id", ALL_NODE_IDS)
def test_haproxy_cfg_matches_committed(node_id: str):
    _, generated = _build_for_node(node_id)
    expected_bytes = (FIXTURE_CONFIGS_DIR / node_id / "haproxy.cfg").read_bytes()
    expected = expected_bytes.replace(b"\r\n", b"\n").decode()
    generated = generated.replace("\r\n", "\n")
    assert generated == expected, (
        f"haproxy.cfg mismatch for {node_id!r}.\n"
        "Regenerate with:\n"
        "  uv run hexrift --yaml tests/fixtures/topology.yaml build --all --haproxy "
        "--keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs"
    )


@pytest.mark.integration
def test_exit_config_structure():
    generated, _ = _build_for_node("nlA00")
    cfg = json.loads(generated)

    # Top-level keys
    for key in ("log", "inbounds", "outbounds", "routing", "dns"):
        assert key in cfg

    # Reality inbound present
    inbound_tags = [ib["tag"] for ib in cfg["inbounds"]]
    assert "direct-xhttp" in inbound_tags

    # CDN inbound present (topology has cdn_xhttp_path for exit region)
    assert "cdn-xhttp" in inbound_tags

    # Standard outbounds present
    outbound_tags = [ob["tag"] for ob in cfg["outbounds"]]
    assert "direct" in outbound_tags
    assert "blocked" in outbound_tags
    assert "warp" in outbound_tags

    # Reality settings use the committed private key
    reality_inbound = next(ib for ib in cfg["inbounds"] if ib["tag"] == "direct-xhttp")
    private_key = reality_inbound["streamSettings"]["realitySettings"]["privateKey"]
    assert private_key == "2M_KKW_6GTmT87r70vuDeqFFmHKy9wmoaADNqUFueGI"

    # Decryption key is ML-KEM-768
    assert reality_inbound["settings"]["decryption"].startswith("mlkem768x25519plus.native.600s.7hyY0")


@pytest.mark.integration
def test_hub_config_structure():
    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)

    # No top-level reverse block (reverse is embedded per portal client)
    assert "reverse" not in cfg

    # Hub inbound has clients for all users + server + guests + portal clients
    direct_ib = next(ib for ib in cfg["inbounds"] if ib["tag"] == "direct-xhttp")
    client_emails = [c["email"] for c in direct_ib["settings"]["clients"]]
    assert "alice@test.hexrift" in client_emails
    assert "alice-server@alice" in client_emails
    assert "bob@test.hexrift" in client_emails
    assert "laptop@bob" in client_emails
    assert "phone@bob" in client_emails
    assert "home@portal.test.hexrift" in client_emails

    # Portal client carries the reverse tag; no catch-all routing rule for it
    portal_client = next(c for c in direct_ib["settings"]["clients"] if c["email"] == "home@portal.test.hexrift")
    assert portal_client.get("reverse") == {"tag": "home-portal"}
    rules = cfg["routing"]["rules"]
    assert not any(r.get("user") == ["home@portal.test.hexrift"] for r in rules)

    # CDN inbound only has cdn-access users (alice has cdn, bob does not)
    cdn_ib = next(ib for ib in cfg["inbounds"] if ib["tag"] == "cdn-xhttp")
    cdn_emails = [c["email"] for c in cdn_ib["settings"]["clients"]]
    assert "alice@test.hexrift" in cdn_emails
    assert "bob@test.hexrift" not in cdn_emails

    # Exit outbound present with correct public key
    outbound_tags = [ob["tag"] for ob in cfg["outbounds"]]
    assert "nlA00" in outbound_tags
    nl_outbound = next(ob for ob in cfg["outbounds"] if ob["tag"] == "nlA00")
    pub_key = nl_outbound["streamSettings"]["realitySettings"]["publicKey"]
    assert pub_key == "2SPCC3V_diQ97Pl6CYnFp52St-k7Mof9PNDPS9D4yRU"

    # Hub short IDs from committed groups
    short_ids = direct_ib["streamSettings"]["realitySettings"]["shortIds"]
    assert "aabbccddeeff0011" in short_ids  # main group explicit short_id
    assert "1122334455667788" in short_ids  # guest group explicit short_id

    # Decryption key is X25519
    assert direct_ib["settings"]["decryption"].startswith("mlkem768x25519plus.native.600s.wLmsb")


@pytest.mark.integration
def test_exit_haproxy_structure():
    _, haproxy = _build_for_node("nlA00")
    assert "bk_reality" in haproxy
    assert "*:443" in haproxy
    assert "[::]:443" in haproxy  # ipv6=true in exit defaults
    assert "crt-store" in haproxy  # CDN configured for nl region


@pytest.mark.integration
def test_hub_haproxy_structure():
    _, haproxy = _build_for_node("mskA00")
    assert "bk_reality" in haproxy
    assert "crt-store" in haproxy  # CDN configured for msk region
    assert "cdn-hub.test.hexrift" in haproxy


@pytest.mark.integration
def test_hub_routing_uses_exit_as_default():
    """hub_default: nl means catch-all routes to nlA00, not back to hub."""

    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    # Last routing rule is the catch-all; its outbound must be an exit node tag
    last_rule = cfg["routing"]["rules"][-1]
    assert last_rule["outboundTag"] == "nlA00"


@pytest.mark.integration
def test_hub_portal_routing_rule():
    """The home portal should appear as a member-filtered routing rule."""

    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    rules = cfg["routing"]["rules"]
    portal_domain_rule = next((r for r in rules if r.get("domain") == ["home.alice.example.com"]), None)
    assert portal_domain_rule is not None
    assert portal_domain_rule["outboundTag"] == "home-portal"
    assert portal_domain_rule["user"] == ["alice@test.hexrift"]


@pytest.mark.integration
def test_hub_direct_routing_rule():
    """hub_routes direct rule for internal.example.com should be present."""

    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    rules = cfg["routing"]["rules"]
    direct_rule = next(
        (r for r in rules if r.get("outboundTag") == "direct" and "internal.example.com" in r.get("domain", [])),
        None,
    )
    assert direct_rule is not None
    assert "internal.example.com" in direct_rule["domain"]


@pytest.mark.integration
def test_exit_client_is_hub_exit_uuid():
    """nlA00's direct inbound should have deterministic hub-exit UUID for mskA00."""

    generated, _ = _build_for_node("nlA00")
    cfg = json.loads(generated)
    clients = cfg["inbounds"][0]["settings"]["clients"]
    assert len(clients) == 1
    assert clients[0]["email"] == "mskA00-nlA00@test.hexrift"
    # UUID is deterministic: uuid5(ns, "mskA00-nlA00")
    assert clients[0]["id"] == "17d3c9f0-7373-5f77-9298-e18c4055e471"


def _build_portal(portal_id: str = "home") -> dict:
    """Build bridge config dict for a portal using committed fixture topology + keys."""

    app = HexRiftApp(yaml_path=FIXTURE_TOPOLOGY)
    cfg = app.schema.config
    hub_node_keys = {
        n.id: app.keys.load_node_keys(n.id, FIXTURE_KEYS_DIR)
        for r in cfg.regions
        if r.type == RegionType.HUB
        for n in r.nodes
    }
    fingerprint = cfg.defaults.hub.exit_connections.fingerprint
    return build_portal_config(cfg, portal_id, hub_node_keys, fingerprint)


@pytest.mark.integration
def test_hub_inbound_order():
    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    assert [ib["tag"] for ib in cfg["inbounds"]] == [
        "direct-xhttp",
        "cdn-xhttp",
        "mixed-inbound",
        "xdns",
        "wireguard-in",
    ]


@pytest.mark.integration
def test_hub_mixed_inbound_present():
    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    mixed = next(ib for ib in cfg["inbounds"] if ib["tag"] == "mixed-inbound")
    assert mixed["port"] == 80
    assert mixed["protocol"] == "mixed"
    assert mixed["settings"]["auth"] == "password"

    # alice has proxy access, bob does not; password is deterministic proxy UUID
    accounts = mixed["settings"]["accounts"]
    assert [a["user"] for a in accounts] == ["alice"]
    assert accounts[0]["pass"] == "4fb83369-f8f1-534f-bf6c-6bd0fdaf2fa6"  # noqa: S105


@pytest.mark.integration
def test_hub_xdns_inbound_present():
    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    inbound_tags = [ib["tag"] for ib in cfg["inbounds"]]
    assert "xdns" in inbound_tags

    xdns_ib = next(ib for ib in cfg["inbounds"] if ib["tag"] == "xdns")
    assert xdns_ib["port"] == 53
    assert xdns_ib["streamSettings"]["network"] == "mkcp"
    assert "kcpSettings" in xdns_ib["streamSettings"]

    finalmask_udp = xdns_ib["streamSettings"]["finalmask"]["udp"]
    assert finalmask_udp[0]["type"] == "xdns"
    assert finalmask_udp[0]["settings"]["domains"] == ["dns.google"]

    assert "trustedXForwardedFor" not in xdns_ib["streamSettings"]["sockopt"]

    emails = {c["email"] for c in xdns_ib["settings"]["clients"]}
    assert emails == {"bob@test.hexrift", "laptop@bob", "phone@bob"}
    assert "alice@test.hexrift" not in emails  # alice lacks xdns access

    # mKCP is non-TLS, so xtls-rprx-vision is invalid; clients must carry empty flow.
    assert all(c["flow"] == "" for c in xdns_ib["settings"]["clients"])


@pytest.mark.integration
def test_hub_wireguard_inbound_present():
    generated, _ = _build_for_node("mskA00")
    cfg = json.loads(generated)
    inbound_tags = [ib["tag"] for ib in cfg["inbounds"]]
    assert "wireguard-in" in inbound_tags

    wg = next(ib for ib in cfg["inbounds"] if ib["tag"] == "wireguard-in")
    assert wg["port"] == 443  # default
    assert wg["protocol"] == "wireguard"
    assert wg["settings"]["mtu"] == 1420  # default
    assert wg["settings"]["secretKey"]  # present, std base64

    peers = wg["settings"]["peers"]
    # alice (user + server), bob (user + 2 guests) → 5 peers, in canonical order.
    assert [p["email"] for p in peers] == [
        "alice@test.hexrift",
        "alice-server@alice",
        "bob@test.hexrift",
        "laptop@bob",
        "phone@bob",
    ]
    assert [p["allowedIPs"][0] for p in peers] == [
        "10.0.0.2/32",
        "10.0.0.3/32",
        "10.0.0.4/32",
        "10.0.0.5/32",
        "10.0.0.6/32",
    ]
    assert all(p["publicKey"] for p in peers)


@pytest.mark.integration
def test_portal_config_structure():
    cfg = json.loads(serialize_config(_build_portal()))

    for key in ("log", "outbounds", "routing"):
        assert key in cfg
    assert "inbounds" not in cfg
    assert "dns" not in cfg


@pytest.mark.integration
def test_portal_config_outbounds():
    cfg = json.loads(serialize_config(_build_portal()))
    tags = [ob["tag"] for ob in cfg["outbounds"]]
    # one per hub node + direct + blocked (strict portal)
    assert "portal-mskA00" in tags
    assert "direct" in tags
    assert tags == ["portal-mskA00", "direct", "blocked"]


@pytest.mark.integration
def test_portal_outbound_uses_hub_hostname():
    """Address must be hub node's hostname."""

    cfg = json.loads(serialize_config(_build_portal()))
    ob = next(o for o in cfg["outbounds"] if o["tag"] == "portal-mskA00")
    assert ob["settings"]["address"] == "mskA00.ap.test.hexrift"


@pytest.mark.integration
def test_portal_outbound_uuid_is_deterministic():
    ns = Namespace("test.hexrift")
    expected_id = str(ns.portal_uuid("home"))

    cfg = json.loads(serialize_config(_build_portal()))
    ob = next(o for o in cfg["outbounds"] if o["tag"] == "portal-mskA00")
    assert ob["settings"]["id"] == expected_id


@pytest.mark.integration
def test_hub_accepts_every_portal_short_id():
    generated, _ = _build_for_node("mskA00")
    ns = Namespace("test.hexrift")
    accepted = json.loads(generated)["inbounds"][0]["streamSettings"]["realitySettings"]["shortIds"]
    assert ns.portal_short_id("home") in accepted
    assert ns.portal_short_id("office") in accepted


@pytest.mark.integration
def test_portal_outbound_reality_settings():
    cfg = json.loads(serialize_config(_build_portal()))
    ob = next(o for o in cfg["outbounds"] if o["tag"] == "portal-mskA00")
    reality = ob["streamSettings"]["realitySettings"]
    assert reality["publicKey"] == "mZ0iHOiFoN3JfGgq_7D7GwvEcMwqJEbT7T5VyqK7Rnk"
    assert reality["fingerprint"] == "chrome"
    assert reality["shortId"] == Namespace("test.hexrift").portal_short_id("home")


@pytest.mark.integration
def test_portal_outbound_reverse_sniffing_off_when_strict():
    # Sniffing would replace the routed address with the client-supplied SNI
    cfg = json.loads(serialize_config(_build_portal()))
    ob = next(o for o in cfg["outbounds"] if o["tag"] == "portal-mskA00")
    reverse = ob["settings"]["reverse"]
    assert reverse["tag"] == "home-portal"
    assert reverse["sniffing"] == {"enabled": False}


@pytest.mark.integration
def test_portal_direct_outbound_allows_reverse_traffic():
    cfg = json.loads(serialize_config(_build_portal()))
    direct = next(o for o in cfg["outbounds"] if o["tag"] == "direct")
    assert direct["settings"]["finalRules"] == [{"action": "allow"}]


@pytest.mark.integration
def test_portal_routing_rules():
    cfg = json.loads(serialize_config(_build_portal()))
    rules = cfg["routing"]["rules"]
    assert len(rules) == 3
    # Emerged reverse traffic egresses directly only for the portal's declared matchers...
    assert rules[0] == {
        "inboundTag": ["home-portal"],
        "domain": ["home.alice.example.com"],
        "outboundTag": "direct",
    }
    # ...anything else off the tunnel is blackholed...
    assert rules[1] == {"inboundTag": ["home-portal"], "outboundTag": "blocked"}
    # ...and the catch-all keeps everything else off the hub-dial outbounds.
    assert rules[2]["network"] == "TCP,UDP"
    assert rules[2]["outboundTag"] == "direct"


@pytest.mark.integration
@pytest.mark.parametrize("portal_id", ["home", "office"])
def test_portal_config_matches_committed(portal_id: str):
    generated = serialize_config(_build_portal(portal_id))
    expected = (FIXTURE_CONFIGS_DIR / "portals" / portal_id / "config.json").read_bytes()
    expected = expected.replace(b"\r\n", b"\n")
    assert generated == expected, (
        f"portal config.json mismatch for portal {portal_id!r}.\n"
        "Regenerate with:\n"
        "  uv run hexrift --yaml tests/fixtures/topology.yaml gen-portal --all "
        "--keys-dir tests/fixtures/keys --out-dir tests/fixtures/configs/portals"
    )


@pytest.mark.integration
def test_multi_member_portal_rule_lists_every_member():
    generated, _ = _build_for_node("mskA00")
    rules = json.loads(generated)["routing"]["rules"]
    rule = next(r for r in rules if r.get("outboundTag") == "office-portal")
    assert rule["user"] == ["alice@test.hexrift", "bob@test.hexrift"]
    assert rule["ip"] == ["10.10.0.0/16"]
